import Mathlib.GroupTheory.Sylow
import Mathlib.GroupTheory.Perm.Cycle.Concrete
import Mathlib.GroupTheory.Perm.Subgroup
import Mathlib.GroupTheory.PresentedGroup

import MIL.Common

/- Monoid and AddCommMonoid -/
-- `Monoid` is a `Semigroup` with identity element `1` such that `x * 1 = x` and `1 * x = x` for all `x`.
example {M : Type*} [Monoid M] (x : M) : x * 1 = x := mul_one x
-- `AddCommMonoid` is an `AddMonoid` with commutative addition.
example {M : Type*} [AddCommMonoid M] (x y : M) : x + y = y + x := add_comm x y

/- Homomorphisms of group -/
-- homomorphism of (multiplicative) monoids which preserves the multiplication and identity element.
example {M N : Type*} [Monoid M] [Monoid N] (x y : M) (f : M →* N) : f (x * y) = f x * f y :=
  f.map_mul x y
example {M N : Type*} [AddMonoid M] [AddMonoid N] (f : M →+ N) : f 0 = 0 :=
  f.map_zero
-- Composition of (additive) monoid homomorphisms `f : M →+ N` and `g : N →+ P` is given by `g.comp f`.
example {M N P : Type*} [AddMonoid M] [AddMonoid N] [AddMonoid P]
    (f : M →+ N) (g : N →+ P) : M →+ P := g.comp f

-- Group and AddCommGroup
example {G : Type*} [Group G] (x : G) : x * x⁻¹ = 1 := mul_inv_cancel x
example {G : Type*} [Group G] (x y z : G) : x * (y * z) * (x * z)⁻¹ * (x * y * x⁻¹)⁻¹ = 1 := by
  group
example {G : Type*} [AddCommGroup G] (x y z : G) : z + x + (y - z - x) = y := by
  abel

-- Homomorphisms of (multiplicative) groups which preserve the multiplication and inverses.
example {G H : Type*} [Group G] [Group H] (x y : G) (f : G →* H) : f (x * y) = f x * f y :=
  f.map_mul x y
example {G H : Type*} [Group G] [Group H] (x : G) (f : G →* H) : f (x⁻¹) = (f x)⁻¹ :=
  f.map_inv x
-- `MonoidHom.mk'` constructs a monoid homomorphism from a function `f` and a proof `h` that `f` preserves multiplication.
example {G H : Type*} [Group G] [Group H] (f : G → H) (h : ∀ x y, f (x * y) = f x * f y) :
    G →* H :=
  MonoidHom.mk' f h

/- Isomorphisms of groups -/
-- Composition of a group isomorphism and its symmetric is the identity isomorphism.
example {G H : Type*} [Group G] [Group H] (f : G ≃* H) :
    f.trans f.symm = MulEquiv.refl G :=
  f.self_trans_symm
-- `MulEquiv.ofBijective` constructs a group isomorphism from a bijective group homomorphism.
noncomputable example {G H : Type*} [Group G] [Group H]
    (f : G →* H) (h : Function.Bijective f) :
    G ≃* H :=
  MulEquiv.ofBijective f h

/- Properties of Subgroup -/
-- Membership in a subgroup is closed under multiplication.
example {G : Type*} [Group G] (H : Subgroup G) {x y : G} (hx : x ∈ H) (hy : y ∈ H) :
    x * y ∈ H :=
  H.mul_mem hx hy
-- Membership in a subgroup is closed under taking inverses.
example {G : Type*} [Group G] (H : Subgroup G) {x : G} (hx : x ∈ H) :
    x⁻¹ ∈ H :=
  H.inv_mem hx

-- Example of the subgroup of rational numbers generated by the integers.
example : AddSubgroup ℚ where
  -- The underlying set of this subgroup is the range of the inclusion map from integers to rationals.
  -- The inclusion map `(↑) : ℤ → ℚ` can be directly treated as an enforced coercion from `ℤ` to `ℚ`.
  carrier := Set.range ((↑) : ℤ → ℚ)
  -- The proof obligations for `AddSubgroup` are provided below.
  -- 1. addition closure
  add_mem' := by
    rintro _ _ ⟨n, rfl⟩ ⟨m, rfl⟩
    use n + m
    simp
  -- 2. existence of zero element
  zero_mem' := by
    use 0
    simp
  -- 3. existence of additive inverses
  neg_mem' := by
    rintro _ ⟨n, rfl⟩
    use -n
    simp

-- Subgroup is also a group
example {G : Type*} [Group G] (H : Subgroup G) : Group H := inferInstance
example {G : Type*} [Group G] (H : Subgroup G) : Group {x : G // x ∈ H} := inferInstance
-- Infimum of subgroups is the intersection set of their underlying sets.
example {G : Type*} [Group G] (H H' : Subgroup G) :
    ((H ⊓ H' : Subgroup G) : Set G) = (H : Set G) ∩ (H' : Set G) := rfl
-- Supremum of subgroups is the subgroup generated by the union of their underlying sets.
example {G : Type*} [Group G] (H H' : Subgroup G) :
    ((H ⊔ H' : Subgroup G) : Set G) = Subgroup.closure ((H : Set G) ∪ (H' : Set G)) := by
  rw [Subgroup.sup_eq_closure]
-- Membership in the top and bottom subgroups.
example {G : Type*} [Group G] (x : G) : x ∈ (⊤ : Subgroup G) := trivial
example {G : Type*} [Group G] (x : G) : x ∈ (⊥ : Subgroup G) ↔ x = 1 := Subgroup.mem_bot
-- Conjugate of a subgroup.
def conjugate {G : Type*} [Group G] (x : G) (H : Subgroup G) : Subgroup G where
  -- The underlying set of the conjugate subgroup consists of elements of the form `x * h * x⁻¹` where `h` is in `H`.
  carrier := {a : G | ∃ h, h ∈ H ∧ a = x * h * x⁻¹}
  -- The proof obligations for the conjugate (multiplicative) subgroup are provided below.
  -- 1. existence of the identity element
  one_mem' := by
    dsimp
    use 1
    constructor
    exact H.one_mem
    group
  -- 2. existence of multiplication inverse
  inv_mem' := by
    dsimp
    rintro - ⟨h, h_in, rfl⟩
    use h⁻¹, H.inv_mem h_in
    group
  -- 3. closure under multiplication
  mul_mem' := by
    dsimp
    rintro - - ⟨h, h_in, rfl⟩ ⟨k, k_in, rfl⟩
    use h*k, H.mul_mem h_in k_in
    group

/- Homomorphisms of subgroups -/
-- The range of a subgroup of source group under a group homomorphism is also a subgroup of the target group.
example {G H : Type*} [Group G] [Group H] (G' : Subgroup G) (f : G →* H) : Subgroup H :=
  Subgroup.map f G'
-- The image of a subgroup of the target group under a group homomorphism is also a subgroup of the source group.
example {G H : Type*} [Group G] [Group H] (H' : Subgroup H) (f : G →* H) : Subgroup G :=
  Subgroup.comap f H'
-- Membership in the image and preimage of a subgroup under a group homomorphism.
#check Subgroup.mem_map
#check Subgroup.mem_comap
-- The membership criterion for the kernel of a group homomorphism.
example {G H : Type*} [Group G] [Group H] (f : G →* H) (g : G) :
    g ∈ MonoidHom.ker f ↔ f g = 1 :=
  f.mem_ker
-- The membership criterion for the range of a group homomorphism.
example {G H : Type*} [Group G] [Group H] (f : G →* H) (h : H) :
    h ∈ MonoidHom.range f ↔ ∃ g : G, f g = h :=
  f.mem_range

section exercises
variable {G H : Type*} [Group G] [Group H]
open Subgroup
-- Monotonicity of the comap and map operations on subgroups.
-- If `S` is a subgroup of `H` and `T` is a subgroup of `H` with `S ≤ T`, then the comap of `S` along a homomorphism `φ` is less than or equal to the comap of `T`.
example (φ : G →* H) (S T : Subgroup H) (hST : S ≤ T) : comap φ S ≤ comap φ T := by
  intro x hx
  rw [mem_comap] at * -- Lean does not need this line
  exact hST hx
-- If `S` is a subgroup of `G` and `T` is a subgroup of `G` with `S ≤ T`, then the map of `S` along a homomorphism `φ` is less than or equal to the map of `T`.
example (φ : G →* H) (S T : Subgroup G) (hST : S ≤ T) : map φ S ≤ map φ T := by
  intro x hx
  rw [mem_map] at * -- Lean does not need this line
  rcases hx with ⟨y, hy, rfl⟩
  use y, hST hy

variable {K : Type*} [Group K]

-- Comap along the composition of two homomorphisms `comap (ψ ∘ φ)` is equal to the comap along the first `comap ψ` followed by the comap along the second `comap φ`.
example (φ : G →* H) (ψ : H →* K) (U : Subgroup K) :
    comap (ψ.comp φ) U = comap φ (comap ψ U) := by
  -- We will use the `ext` tactic to prove an equality of subgroups.
  -- The whole proof could be ``rfl``, but let's decompose it a bit.
  ext x
  simp only [mem_comap]
  rfl

-- Map along the composition of two homomorphisms `map (ψ ∘ φ)` is equal to the map along the second `map φ` followed by the map along the first `map ψ`.
example (φ : G →* H) (ψ : H →* K) (S : Subgroup G) :
    map (ψ.comp φ) S = map ψ (S.map φ) := by
  ext x
  simp only [mem_map]
  constructor
  · rintro ⟨y, y_in, hy⟩
    exact ⟨φ y, ⟨y, y_in, rfl⟩, hy⟩
  · rintro ⟨y, ⟨z, z_in, hz⟩, hy⟩
    use z, z_in
    calc ψ.comp φ z = ψ (φ z) := rfl
    _               = ψ y := by congr
    _               = x := hy

end exercises

open scoped Classical

-- Theorem : The cardinality of a subgroup divides the cardinality of the whole group.
-- `Subgroup.index` is defined as the quotient of the cardinality of the whole group by the cardinality of the subgroup.
-- `Nat.card G' | Nat.card G` implies `∃ k, Nat.card G = Nat.card G' * k`, where `k` is the index of subgroup `G'`, i.e. `k = G'.index`
-- `h ▸ e` means we are rewriting `e` using the equality `h`.
example {G : Type*} [Group G] (G' : Subgroup G) : Nat.card G' ∣ Nat.card G :=
  ⟨G'.index, mul_comm G'.index _ ▸ G'.index_mul_card.symm⟩

open Subgroup

-- Sylow's theorem : For a finite group `G` and a prime `p`, if `p^n` divides the order of `G`, then there exists a subgroup of `G` of order `p^n`.
example {G : Type*} [Group G] [Finite G] (p : ℕ) {n : ℕ} [Fact p.Prime]
    (hdvd : p ^ n ∣ Nat.card G) : ∃ K : Subgroup G, Nat.card K = p ^ n :=
  Sylow.exists_subgroup_card_pow_prime p hdvd

-- A subgroup is trivial (equal to the bottom subgroup) if and only if its cardinality is 1.
lemma eq_bot_iff_card {G : Type*} [Group G] {H : Subgroup G} :
    H = ⊥ ↔ Nat.card H = 1 := by
  suffices (∀ x ∈ H, x = 1) ↔ ∃ x ∈ H, ∀ a ∈ H, a = x by
    simpa [eq_bot_iff_forall, Nat.card_eq_one_iff_exists]
  constructor
  · intro h
    use 1, H.one_mem
  · rintro ⟨y, -, hy'⟩ x hx
    calc x = y := hy' x hx
    _      = 1 := (hy' 1 H.one_mem).symm

-- If two subgroups has the relationship `≤`, then the cardinality of the smaller subgroup divides the cardinality of the larger subgroup.
#check card_dvd_of_le

-- Theorem : If two subgroups have coprime cardinalities, then their intersection is trivial.
lemma inf_bot_of_coprime {G : Type*} [Group G] (H K : Subgroup G)
    (h : (Nat.card H).Coprime (Nat.card K)) : H ⊓ K = ⊥ := by
  have D₁ : Nat.card (H ⊓ K : Subgroup G) ∣ Nat.card H := card_dvd_of_le inf_le_left
  have D₂ : Nat.card (H ⊓ K : Subgroup G) ∣ Nat.card K := card_dvd_of_le inf_le_right
  exact eq_bot_iff_card.2 (Nat.eq_one_of_dvd_coprimes h D₁ D₂)

/- Quotient groups and related isomorphisms -/
noncomputable section QuotientGroup
-- If `H` is a normal subgroup of `G`, then the quotient `G ⧸ H` forms a group.
-- `Normal` is a special case of a subgroup that is invariant under conjugation by elements of the group.
example {G : Type*} [Group G] (H : Subgroup G) [H.Normal] : Group (G ⧸ H) := inferInstance
-- `QuotientGroup.mk'` gives the canonical projection from `G` to `G ⧸ H` where `H` is a normal subgroup.
example {G : Type*} [Group G] (H : Subgroup G) [H.Normal] : G →* G ⧸ H :=
  QuotientGroup.mk' H
-- `QuotientGroup.lift` gives a homomorphism from the quotient `G ⧸ N` to `M` induced by a homomorphism `φ : G →* M` that kills normal subgroup `N`, where `h : N ≤ MonoidHom.ker φ` ensures that `φ` kills `N`.
-- In other words, `QuotientGroup.lift` allows us to factor a homomorphism through the quotient by its kernel.
example {G : Type*} [Group G] (N : Subgroup G) [N.Normal] {M : Type*}
    [Group M] (φ : G →* M) (h : N ≤ MonoidHom.ker φ) : G ⧸ N →* M :=
  QuotientGroup.lift N φ h
-- `QuotientGroup.quotientKerEquivRange` gives an isomorphism between the quotient `G ⧸ ker φ` and the range of `φ`.
example {G : Type*} [Group G] {M : Type*} [Group M] (φ : G →* M) :
    G ⧸ MonoidHom.ker φ →* MonoidHom.range φ :=
  QuotientGroup.quotientKerEquivRange φ
-- `QuotientGroup.map` gives a homomorphism from `G ⧸ N` to `G' ⧸ N'` induced by a homomorphism `φ : G →* G'` that maps `N` into `N'`.
-- where `N` and `N'` are normal subgroups of `G` and `G'` respectively.
example {G G': Type*} [Group G] [Group G']
    {N : Subgroup G} [N.Normal] {N' : Subgroup G'} [N'.Normal]
    {φ : G →* G'} (h : N ≤ Subgroup.comap φ N') : G ⧸ N →* G' ⧸ N':=
  QuotientGroup.map N N' φ h
-- `QuotientGroup.quotientMulEquivOfEq` gives an isomorphism between the quotients `G ⧸ M` and `G ⧸ N` when `M = N`.
example {G : Type*} [Group G] {M N : Subgroup G} [M.Normal]
    [N.Normal] (h : M = N) : G ⧸ M ≃* G ⧸ N := QuotientGroup.quotientMulEquivOfEq h

section
variable {G : Type*} [Group G] {H K : Subgroup G}

open MonoidHom
-- The cardinality should be positive
#check Nat.card_pos -- The nonempty argument will be automatically inferred for subgroups
-- The index of a subgroup equals the cardinality of the quotient group corresponding to that subgroup.
#check Subgroup.index_eq_card
-- The product of the index of a subgroup and the cardinality of the subgroup equals the cardinality of the whole group.
#check Subgroup.index_mul_card
#check Nat.eq_of_mul_eq_mul_right

-- Auxiliary lemma to relate the cardinality of the quotient group `G ⧸ H` with the cardinality of `K` when `G` is finite and `Nat.card G = Nat.card H * Nat.card K`.
lemma aux_card_eq [Finite G] (h' : Nat.card G = Nat.card H * Nat.card K) :
    Nat.card (G ⧸ H) = Nat.card K := by
  have := calc
    Nat.card (G ⧸ H) * Nat.card H = Nat.card G := by rw [← H.index_eq_card, H.index_mul_card]
    _                             = Nat.card K * Nat.card H := by rw [h', mul_comm]

  exact Nat.eq_of_mul_eq_mul_right Nat.card_pos this

variable [H.Normal] [K.Normal] [Fintype G] (h : Disjoint H K)
  (h' : Nat.card G = Nat.card H * Nat.card K)

-- Given a function `f : α → β`, it is bijective iff it is injective and the cardinality of `α` equals the cardinality of `β`.
#check Nat.bijective_iff_injective_and_card
-- The kernel of a homomorphism is trivial iff the homomorphism is injective.
#check ker_eq_bot_iff
#check restrict
-- The kernel of the restriction of a homomorphism to a subgroup equals the intersection of the kernel of the homomorphism with the subgroup.
#check ker_restrict

-- Given `H` and `K` are normal subgroups of `G` and `H` is disjoint from `K`.
-- The first theorem of group isomorphism between `K` and `G ⧸ H`.
def iso₁ : K ≃* G ⧸ H := by
  apply MulEquiv.ofBijective ((QuotientGroup.mk' H).restrict K)
  rw [Nat.bijective_iff_injective_and_card]
  constructor
  · rw [← ker_eq_bot_iff, (QuotientGroup.mk' H).ker_restrict K]
    simp [h]
  · symm
    exact aux_card_eq h'

-- The second theorem of group isomorphism between `G` and the product `(G ⧸ K) × (G ⧸ H)`.
def iso₂ : G ≃* (G ⧸ K) × (G ⧸ H) := by
  apply MulEquiv.ofBijective <| (QuotientGroup.mk' K).prod (QuotientGroup.mk' H)
  rw [Nat.bijective_iff_injective_and_card]
  constructor
  · rw [← ker_eq_bot_iff, ker_prod]
    simp [h.symm.eq_bot]
  · rw [Nat.card_prod]
    rw [aux_card_eq h', aux_card_eq (mul_comm (Nat.card H) _▸ h'), h']

-- The last theorem of group isomorphism between `G` and the product `H × K`.
def finalIso : G ≃* H × K :=
  (iso₂ h h').trans ((iso₁ h.symm (mul_comm (Nat.card H) _ ▸ h')).prodCongr (iso₁ h h')).symm

end
end QuotientGroup
